sudo: false
language: csharp
mono:
 - latest
solution: adaptive-arp-api.sln
before_install: cd adaptive-arp-api
after_success:
 - cd ..
 - echo Home is: $HOME
 - pwd
 - ls -Rlart
install:
 - nuget restore adaptive-arp-api.sln
script:
 - xbuild /p:Configuration=Release adaptive-arp-api.sln
cache:
 directories:
  - /home/travis/build/AdaptiveMe/adaptive-arp-api-lib-dotnet/adaptive-arp-api/packages
