sudo: false
language: csharp
mono:
 - latest
solution: adaptive-arp-api.sln
before_install: cd adaptive-arp-api
install:
- nuget restore adaptive-arp-api.sln
script:
- xbuild /p:Configuration=Release adaptive-arp-api.sln
