sudo: false
language: csharp
mono:
- latest
solution: adaptive-arp-api.sln
before_install:
- cd adaptive-arp-api
- export GIT_TAG=`git describe --abbrev=0`
- mono ./tools/changeVersionNuget.exe -p adaptive-arp-api.nuspec -v $GIT_TAG
- mono ./tools/changeSourcesProject.exe -p adaptive-arp-api.csproj -s Sources/
before_script:
- export HOME=`pwd`
- export TIMESTAMP=`date`
- export CURRENT_TAG=`git describe --abbrev=0`
- mkdir -p .git
- git config --global credential.helper "store --file=$HOME/.git/credentials"
- git config --global user.email "carlos@adaptive.me"
- git config --global user.name "carloslozano"
- git config --global push.default simple
- echo "https://${GH_TOKEN}:@github.com" > $HOME/.git/credentials
after_success:
  if [ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    - nuget pack adaptive-arp-api.nuspec
    - nuget setApiKey $API_KEY
    - nuget push AdaptiveMe.Api.$GIT_TAG.nupkg
  elif [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    - nuget pack adaptive-arp-api.nuspec
    - git remote set-url origin https://github.com/AdaptiveMe/adaptive-arp-api-lib-dotnet.git
    - git add -u
    - git commit -m "Auto-updated project from sources."
    - git push origin HEAD:master
  else
    - nuget pack adaptive-arp-api.nuspec
  fi
install:
- nuget restore adaptive-arp-api.sln
script:
- xbuild /p:Configuration=Release adaptive-arp-api.sln
cache:
  directories:
  - /home/travis/build/AdaptiveMe/adaptive-arp-api-lib-dotnet/adaptive-arp-api/packages
env:
  global:
    secure: Nr2+dNeBKK9dKdyA97Ib3K3wCXPQTwz2jBdKPAHd5lPFF6GvBvgibaEZ5g5Yz5yPJmS9yTcfBQhTpymnuSh6hd0r1wiy3WZIvzmfvmD+aF54g95BjjeyYzpOK6+2DHyJnTM6huvEeoTyL61H8ZqKz2aT3ggakwoswXRcKGcon90=
